# Generated by Django 5.1.4 on 2024-12-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='title', max_length=150, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='blog')),
            ],
        ),
    ]
